# Font
font_family FiraCode Nerd Font Mono
font_size 9.7
modify_font cell_width 96%
modify_font cell_height -3px
modify_font baseline 2

# Cursor
cursor_trail 1
cursor_trail_start_threshold 0
# Keep the block cursor at the shell prompt
shell_integration no-cursor

# Performance
repaint_delay 8
input_delay 0
sync_to_monitor no

# Layout
enabled_layouts grid

include ./themes/kanagawa.conf
